version: '1.0.0.build{build}'
configuration:
- Debug
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  COVERALLS_REPO_TOKEN:
    secure: MVvYQBGULYonZ2Kl14jFKBLrrgrdurIi0iwQdUK6kiGsHegGjk+KMytjYL//6uWi
  OPENCOVER_CONSOLE: '%USERPROFILE%/.nuget/packages/OpenCover.4.6.519/tools/OpenCover.Console.exe'
  XUNIT_CONSOLE: '%USERPROFILE%/.nuget/packages/xunit.runner.console/2.1.0/tools/xunit.console.exe'
  OPENCOVER_TARGETDIR: './test/bin/Debug/netcoreapp1.0/'
  OPENCOVER_SEARCHDIRS: '%USERPROFILE%/.nuget/packages'
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
#- nuget restore -PackagesDirectory packages
- appveyor-retry dotnet restore -v Minimal #Debug
build_script:
- dotnet build "src/Console" -c %CONFIGURATION% --version-suffix %LABEL%
- dotnet build "test" -c %CONFIGURATION% --version-suffix %LABEL%
after_build:
- dotnet publish "src/Console" -c %CONFIGURATION% --version-suffix %LABEL% -o artifacts\Console
- dotnet publish "test" -c %CONFIGURATION% --version-suffix %LABEL% -o artifacts\Console
test_script:
- dotnet test "test" -c %CONFIGURATION%
artifacts:
- path: artifacts\**\*.*
cache:
- '%USERPROFILE%\.nuget\packages'
on_finish: # Run the demo to show that it works
- dotnet artifacts\Console\Console.dll